services:
  supportbot:
    build: .
    restart: unless-stopped
    volumes:
      - /data/coolify/applications/vk0skow/config:/bot/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    ports:
      - 8080
    networks:
      - coolify

networks:
  coolify:
    external: true
